services:
  postgres:
    build:
      context: ./services/db
    container_name: udg_postgres_db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: university
    volumes:
      - ./services/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  file_generator:
    build:
      context: ./services/file_generator
    container_name: udg_file_generator
    volumes:
      - ./services/file_generator/output:/app/output

  nifi:
    image: apache/nifi:1.19.1
    container_name: udg_nifi
    ports:
      - "8080:8080"
      - "8181:8181"
      - "8443:8443"
      - "10000:10000"
    volumes:
      - type: volume
        source: conf
        target: /opt/nifi/current/conf
      - type: volume
        source: content
        target: /opt/nifi/current/content_repository
      - type: volume
        source: db
        target: /opt/nifi/current/database_repository
      - type: volume
        source: flowfile
        target: /opt/nifi/current/flowfile_repository
      - type: volume
        source: provenance
        target: /opt/nifi/current/provenance_repository
      - type: volume
        source: logs
        target: /opt/nifi/current/logs
      - type: volume
        source: data
        target: /opt/nifi/current/data
      - ./services/file_generator/output:/input_files
      - ./services/nifi/lib:/opt/nifi/lib

volumes:
  conf:
  content:
  db:
  flowfile:
  provenance:
  logs:
  data:
